### ISSUE TITLE
Allow a configuration file to store scrub defaults

### ISSUE THREAD

**Issue by pete4abw** [chaos/scrub#15]
Feature addition.
**$HOME/.scrub.conf** will contain certain constants for scrub making command-line usage easier.
Constants that can be set are:

* **PATTERN** = valid pattern name excl custom (-p pat)
* **NOSIGNATURE** = 0,1,FALSE,TRUE (-S)
* **REMOVE** = 0,1,FALSE,TRUE (-r)
* **NOLINK** = 0,1,FALSE,TRUE (-L)
* **NOHWRAND** = 0,1,FALSE,TRUE (-R)
* **NOTHREADS** = 0,1,FALSE,TRUE (-t)
   valid patterns are: nnsa, dod, bsi, usarmy, random, random2, schneier, pfitzner7, pfitzner33, gutmann, fastold, old, dirent, fillzero, fillff, verify 
custom pattern strings not accepted

### Functional Specification
If file **$HOME/.scrub.conf **exists, it will be read on scrub invocation.
If any keyword is misspelled, not included in valid set, or has an invalid value, an error will be reported and program will abort.
If keywords are set in scrub.conf, those values will be read in to the **opt** structure.
All keywords in scrub.conf are optional and can be omitted or commented out.

**Any command-line option will override options stored in scrub.conf.**
**usage** function will display values provided by scrub.conf if the file exists (see _dod_ below). 
>scrub.conf file
**PATTERN**=dod
**FORCE**=0
**NOSIGNATURE**=0
**REMOVE**=0
**NOLINK**=TRUE
**NOHWRAND**=TRUE
**NOTHREADS**=0

> Using options from scrub.conf
Usage: scrub [OPTIONS] file [file...]
   -p, --pattern pat       select scrub pattern sequence (default _dod_)
 
**usage** function should indicate default value whether provided by **scrub** program or by scrub.conf file.
![usage_using_scrub conf](https://user-images.githubusercontent.com/10359685/51535068-0fccd100-1e0d-11e9-9c9b-b90f6bdbfe9c.jpg)

**Comment by garlick** [comment]
I would rather not add a config file for scrub right now Peter - I have no time to review/codesign this right now, and there is no strong motivation for it that I can see.

**Comment by pete4abw** [comment]
I had already forked a version for it, but the recent changes required some additional merging. So I reset and decided to propose the idea again. No worries, I'll just branch off.
