### ISSUE TITLE
Do not Cross Mount Points (into SSD partitions)

### ISSUE THREAD

**Issue by stef204** [chaos/scrub#26]
How does one use the `-X` option, for example, in such a way that `scrub` does not cross mount points (into mounted partitions on an SSD)?

Example:

```
# cd /
# scrub -X erase
```
if there is an SSD mounted on `/mnt/ssX`?

**Comment by garlick** [comment]
`scrub -X PATH` doesn't traverse the file tree.  It just creates `PATH` as a directory, and fills it with junk to try to overwrite all the free space in the file system.

**Comment by stef204** [comment]
OK, thanks. let's close this.
